name: "CI"
on:
  push:
    branches:
      - master
  pull_request:

env:
  TEST_IMAGE_NAME: godacov-action:${{github.sha}}

jobs:
  lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run hadolint
        run: hadolint Dockerfile

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: ["lint"]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t $TEST_IMAGE_NAME .

      - name: Run Structure tests
        uses: brpaz/structure-tests-action@v1.1.1
        with:
          image: $TEST_IMAGE_NAME

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: brpaz/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
